parameters:
  nd.symfony.fixtures.generator.class: NorseDigital\Symfony\RestBundle\Fixture\FixtureGenerator
  nd.symfony.listener.class: NorseDigital\Symfony\RestBundle\Event\Kernel\HttpKernelExceptionListener

services:
  nd.symfony.fixtures.generator:
    class: "%nd.symfony.fixtures.generator.class%"

  nd.symfony.kernel.listener:
      class: "%nd.symfony.listener.class%"
      tags:
          - { name: kernel.event_subscriber }