parameters:
  core.service.nd_fixture.generator.class: NorseDigital\Symfony\RestBundle\Fixture\FixtureGenerator
  api.kernel.listener.class: NorseDigital\Symfony\RestBundle\Event\Kernel\HttpKernelExceptionListener

services:
  core.service.nd_fixture_generator:
    class: "%core.service.nd_fixture.generator.class%"

  api.kernel.listener:
      class: "%api.kernel.listener.class%"
      tags:
          - { name: kernel.event_subscriber }